export const FETCH_CHATROOMS_START = 'FETCH_CHATROOMS_START';
export const FETCH_CHATROOMS_SUCCESS = 'FETCH_CHATROOMS_SUCCESS';
export const FETCH_CHATROOMS_ERROR = 'FETCH_CHATROOMS_ERROR';

export const FETCH_CHATROOM_MESSAGES_START = 'FETCH_CHATROOM_MESSAGES_START';
export const FETCH_CHATROOM_MESSAGES_SUCCESS = 'FETCH_CHATROOM_MESSAGES_SUCCESS';
export const FETCH_CHATROOM_MESSAGES_ERROR = 'FETCH_CHATROOM_MESSAGES_ERROR';

export const ADD_MESSAGE = 'ADD_MESSAGE';
export const SEND_MESSAGE_ERROR = 'SEND_MESSAGE_ERROR';
